name: Lint and Style Check
on:
  push:
    branches:
      - main
jobs:
  lint_and_style_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
        
      - name: execute py script
        uses: datapane/build-action@v2
        with:
          script: "app.py"
